synthetic-package: false

# The files are generated into the path specified by `arb-dir`
arb-dir: lib/i18n

output-dir: lib/i18n/generated

template-arb-file: app_en.arb

output-localization-file: app_localizations.dart